name: build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Create tag
        run: echo "tag=$(date +%s)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: install ares-cli
        run: |
          npm install -g @webosose/ares-cli

      - name: build web and app
        run: |
          make build

      - name: publish app
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.tag}}
          files: |
            dist/tv.cesium.app_*_all.ipk

      - name: build and push web
        run: |
          docker build -f docker/web/Dockerfile \
            --push \
            --tag ${{secrets.DOCKER_ORG}}/console:latest \
            --tag ${{secrets.DOCKER_ORG}}/console:${{env.tag}} \
            --platform linux/amd64 .
